project: "Design Methods"
name: methods
github:
- Bixal/methods
description: A collection of design and research methods, including general descriptions and how-tos, to share how we work and build a common design vocabulary, inspired by 18F.
stage: beta
milestones:
- "February 2020: Conducted internal workshop using 18F Methods as a starting point for our own toolkit."
contact:
- Bixal/methods/issues
team: philip, katharine, emilia, russ, andrew, sofya, sofia
licenses:
  methods: Public Domain (CC0)
links:
- https://bixal.github.io/methods/index.html
blog:

status:
