markdown: kramdown
kramdown:
  parse_block_html: true
name: Methods
exclude:
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- go
- vendor

permalink: pretty
highlighter: rouge

sass:
  style: compressed

collections:
  methods:
    output: true
    permalink: /:path/

site:
  title: Bixal Methods

title: Bixal Methods

description: A guide to help practice and promote human-centered design and agile delivery to improve outcomes.

repos:
- name: Methods
  description: Main repository
  url: https://github.com/Bixal/methods

jekyll_get:
  - data: releases
    json: 'https://api.github.com/repos/Bixal/methods/releases'

plugins:
  - jekyll-last-modified-at
  - jemoji
  - jekyll-mentions
  - jekyll-redirect-from

google_analytics_ua: null
